[build]
publish = "public"
command = "npm run build"

[[redirects]]
  from = "/index.html"
  to = "https://geeksimple.netlify.app/"
  status = 200
  force = false
  query = {path = ":path"}
  conditions = {Language = ["en"], Country = ["US"], Role = ["admin"]}