[build]
publish = "public"
command = "npm run build"

[[redirects]]
  from = "/index.html"
  to = "/new-path"
  status = 301
  force = false
  query = {path = ":path"}
  conditions = {Language = ["en"], Country = ["US"], Role = ["admin"]}